version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaGitTest3006251032Project
  gitServerName: Kusi_VCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
